name: CI

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write
  security-events: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wow-look-at-my/go-toolchain@v1
        with:
          autorelease: 'true'

  manifest:
    needs: ci
    uses: ./.github/workflows/deploy-manifest.yml
    with:
      org: wow-look-at-my
